# Generated by Django 4.1 on 2022-09-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('role', models.CharField(choices=[('responsable informatique', 'Responsable Informatique'), ('chargee affaire', 'Chargee Affaire'), ('responsable logistique1', 'Responsable Logistique 1'), ('responsable financier', 'Responsable Financier'), ('responsable logistique2', 'Responsable Logistique 2')], max_length=100, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RchA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_Dossier', models.IntegerField()),
                ('fournisseur', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('date_VCL', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='RespoFin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_capf', models.DateTimeField()),
                ('date_capp', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='RespoINf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cacrs', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='RL1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_Imp', models.CharField(choices=[('en_negociation', 'En Negociation'), ('confirmee_fourn', 'Confirmee Fourn'), ('ex_c_payement', 'Ex_C_Payement'), ('en_preparation', 'En Preparation'), ('prelevee', 'Prelevee'), ('arrivee_maroc', 'Arrivee Maroc'), ('en_dedouanement', 'En Dedouanement'), ('liquide', 'Liquide'), ('en_entrepot', 'En Entrepot'), ('livree', 'Livree'), ('cloturee', 'Cloturee')], default='en_negociation', max_length=20)),
                ('date_TCS', models.DateTimeField()),
                ('code_Four_Sage', models.IntegerField()),
                ('ref_Bon_Cmd_Sage', models.CharField(max_length=200)),
                ('cat_Cmd', models.CharField(max_length=200)),
                ('date_CCF', models.DateTimeField()),
                ('n_FP', models.IntegerField()),
                ('date_FP', models.DateTimeField()),
                ('pays_Origine', models.CharField(max_length=200)),
                ('incoterm', models.CharField(max_length=200)),
                ('pays_Prt', models.CharField(max_length=200)),
                ('montant_Dev', models.IntegerField()),
                ('devise', models.CharField(max_length=200)),
                ('mode_Pay', models.CharField(max_length=200)),
                ('delai_Liv', models.CharField(max_length=200)),
                ('Exec_Co_Pay', models.CharField(max_length=200)),
                ('date_PPF', models.DateField()),
                ('date_PAM', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='RL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pickup', models.DateTimeField()),
                ('freightforward', models.CharField(max_length=100)),
                ('mode_trans', models.CharField(max_length=100)),
                ('date_AM', models.CharField(max_length=100)),
                ('transitaire', models.CharField(max_length=100)),
                ('Mt_ded_dh', models.CharField(max_length=100)),
                ('date_ld', models.DateTimeField()),
                ('date_lc', models.DateTimeField()),
                ('litige', models.CharField(max_length=100)),
                ('class_litige', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='GeneralDTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respo_ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.rcha')),
                ('respo_financier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.respofin')),
                ('respo_informatique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.respoinf')),
                ('respo_logistique_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.rl1')),
                ('respo_logistique_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.rl2')),
            ],
        ),
    ]
