# Generated by Django 4.1 on 2022-09-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldtable',
            name='respo_ca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.rcha'),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='respo_financier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.respofin'),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='respo_informatique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.respoinf'),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='respo_logistique_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.rl1'),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='respo_logistique_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.rl2'),
        ),
    ]
